spring:
  batch:
    job:
      enabled: true
      name: exampleJob
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio
    username: root
    password: 1541
#    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true

